### ISSUE TITLE
Function in C API needs proper declaration

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#477]
[This macro in `nmatrix.h`](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/nmatrix.h#L369) gives a warning like this when the macro is used in another file:

```
warning: implicit declaration of function ‘nm_storage_count_max_elements’ [-Wimplicit-function-declaration]
```

Declaring C and C++ variants of the `nm_storage_count_max_elements` function should do the trick.

**Comment by wlevine** [comment]
Can't you just include the header file where this is defined
(storage/common.h)? I don't see this warning so I can't verify if this
works.

**Comment by v0dro** [comment]
`common.h` is intended to be a header for a C++ file so it won't function properly when using GCC for compiling `nmatrix.h`. You can reproduce the error by calling the macro in an external library and including `nmatrix.h`.

**Comment by edmundhighcock** [comment]
This is an issue for me too. Could we please have the declaration of nm_storage_count_max_elements in the publicly available C header file (that is, nmatrix.h)?

**Comment by edmundhighcock** [comment]
I have added the declaration to my own code for now, but in theory the macro should be independent of the implementation. I am now tied to the particular form of `nm_storage_count_max_elements`.

As ever, thanks in advance.

**Comment by mohawkjohn** [comment]
It's the one on line 391, not 369, right?

**Comment by mohawkjohn** [comment]
Why is it you think we need C and C++ variants? It seems like it should be sufficient to just add

```
size_t nm_storage_count_max_elements(const STORAGE* storage);
```

around line 445. I don't think it needs to be before the macro declaration since the macro isn't a function — we just need to ensure that anyone who includes nmatrix.h and uses the macro has access to the function declaration.

**Comment by edmundhighcock** [comment]
I’m talking about the declaration on line 74 of storage/common.h, needed by the macro NM_DENSE_COUNT on line 354 of nmatrix.h in my version (0.2.1)

Thanks,

Edmund

**Comment by mohawkjohn** [comment]
Sorry, yes, that question was addressed to @v0dro, not you @edmundhighcock.

**Comment by edmundhighcock** [comment]
I think @v0dro is also using the C API, since he mentions using GCC: I think he was merely pointing out that including storage.h would only work for C++. Presumably @mohawkjohn's solution will work for both C and C++ if surrounded by the appropriate # ifdef cplusplus extern formalism.

**Comment by v0dro** [comment]
I'm using plain gcc. Its this line: https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/nmatrix.h#L391

**Comment by mohawkjohn** [comment]
@edmundhighcock Actually, the header file is for both C and C++, so it has
to be compatible with both. We accomplish this using a lot of macros.

**Comment by shailesh210** [comment]
Hi,
Is this issue still open? If yes, I would like to help.

**Comment by mohawkjohn** [comment]
Yes, still open. But @shailesh210, please pick one issue at a time. We're thrilled to have you contribute on multiple issues, but there's no need to hoard them. :)

**Comment by NakulVaidya** [comment]
hello, as this issue is still open I would like to work on it.

**Comment by NakulVaidya** [comment]
I tried to compile nmatrix/ext/nmatrix/nmatrix.cpp
I got this error:
nmatrix.cpp:34:18: fatal error: ruby.h: No such file or directory
 #include <ruby.h>
                  ^
compilation terminated.

I tried running these commands :
$ sudo apt-get install ruby-dev
$ sudo apt-get install ruby2.3-dev
$ gem install rerun
gcc is already installed

I am working on ubuntu 16.10
output for: ruby -v 
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

**Comment by mohawkjohn** [comment]
@NakulVaidya Please open a separate issue, or ask on the Google Group.

(For one thing, I'd strongly suggest using rbenv and ruby-build, or at least rvm, instead of installing with apt. It's definitely not finding your dev headers, but I don't really know why. I'll delete these last two messages once you've opened a new issue or asked elsewhere.)

**Comment by mohawkjohn** [comment]
@NakulVaidya Yes, issue is still open.

**Comment by shailesh210** [comment]
Hi @NakulVaidya 
Are you working on this issue?
